//WINDOW ACTIONS
export const CREATE_WINDOW = "CREATE_WINDOW";
export const DELETE_WINDOW = "DELETE_WINDOW";
export const MINIMIZE_WINDOW = "MINIMIZE_WINDOW";
export const ACTIVATE_WINDOW = "ACTIVATE_WINDOW";

//CALCULATOR ACTIONS
export const calculatorActionTypes = {
  INSERT_NUMBER: "INSERT_NUMBER",
  INSERT_OPERATOR: "INSERT_OPERATOR",
  INSERT_INPUT: "INSERT_INPUT",
  SOLVE: "SOLVE",
  RESET_CALCULATOR: "RESET_CALCULATOR",
  RESET_ACTION_HISTORY: "RESET_ACTION_HISTORY",
  CLEAR_CURRENT_VALUE: "CLEAR_CURRENT_VALUE",
  BACKSPACE: "BACKSPACE",
  FIND_ADDITIVE_INVERSE: "FIND_ADDITIVE_INVERSE",
  INSERT_DECIMAL: "INSERT_DECIMAL",
  CREATE_CALCULATOR: "CREATE_CALCULATOR",
  REMOVE_CALCULATOR_STATE: "REMOVE_CALCULATOR_STATE"
};

export const redditAuthActionTypes = {
  __AUTHENTICATE_APP__: {
    REQUEST: "AA_REQUEST",
    SUCCESS: "AA_SUCCESS",
    FAILURE: "AA_FAILURE"
  },
  __REFRESH_TOKEN__: {
    REQUEST: "RT_REQUEST",
    SUCCESS: "RT_SUCCESS",
    FAILURE: "RT_FAILURE"
  }
};

export const redditActionTypes = {
  CREATE_REDDIT_BROWSER: "CREATE_REDDIT_BROWSER",
  REMOVE_REDDIT_BROWSER: "REMOVE_REDDIT_BROWSER",
  __FETCH_POSTS__: {
    REQUEST: "FP_REQUEST",
    SUCCESS: "FP_SUCCESS",
    FAILURE: "FP_FAILURE"
  }
};

export const navigationActionTypes = {
  TOGGLE_NAVIGATION_BAR: "TOGGLE_NAVIGATION_BAR"
};
